### ISSUE TITLE
super basic elliptical galaxy function

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/ScopeSim_Templates#2]
Basic description
* A function which creates an image following an sersic N=4 [or varying?] profile for a given distance
* A set spectrum with a low velocity dispersion can be associated with it

Settable parameters 
* Dimensions (semi-major, semi-minor axis), ellipticity, angle
* Velocity dispersion - this should alter the associated spectum (i.e. with a LSF)
* Total Flux - in mags, or Jansky, or erg/s, or surface brightness
* pixel_scale [arcsec]

Should return a ``scopesim.Source`` object with 
* a single ``ImageHDU`` in the ``.fields`` list
* a single ``SourceSpectrum`` in the ``.spectra`` list

**Comment by miguelverdugo** [comment]
OK. Let's do a test of this as a particular case.
