### ISSUE TITLE
Undefined function in scopesim_templates.basic.stars.cluster()

### ISSUE THREAD

**Issue by yosata** [AstarVienna/ScopeSim_Templates#3]
Line 251-260 of stars.py uses a `find_file()` function that is undefined when running it.

Some guesses:
1. I suspect that the datafile "IMF_1E4.dat" and "IMF_1E5.dat"  (line 252 and line 256) will not be found, although I have not checked that.
2. I suspect that there there will be more functions that are not defined properly when running. E.g. `_get_stellar_mass()` (line 265), `_get_stellar_Mv()` (line 272) and `_scale_pickles_to_photons()` (line 278). 

Is this code perhaps copied from a different file without the necessary dependencies?

**Comment by teutoburg** [comment]
I don't think this is still an issue as of v0.4.4, I am unable to find any of the functions referenced here. In case I am mistaken, and the issue _does_ still exist, please reopen the issues...
