### ISSUE TITLE
Fix ReadTheDocs

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/ScopeSim_Templates#50]
https://scopesim_templates.readthedocs.io/en/latest says "Bad Request (400)"

**Comment by teutoburg** [comment]
Using a `-` instead of `_` works fine now. Should we close this?

**Comment by hugobuddel** [comment]
I don't even recall opening this.. (But perhaps that's what I use issue tracker for; to get things out of my head.) Thanks for fixing it
