### ISSUE TITLE
MICADO: Create Pin Hole Mask 'source' templates

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/ScopeSim_Templates#6]
We'd like to simulate MICADO data using pin hole masks. There are two ways to do this (see discussion in astronomyk/ScopeSim#23 ):

* The easy way would be here as the mask is a "quasi" source, it's simulating a grid of point sources.
* The less easy way (but self-consistent) would be to make an Effect for the pinhole mask, and use the flat-field source object.

This issue is to do the easy way: creating a quasi source with a grid of pointsources.

**Comment by teutoburg** [comment]
Closing this as the pinhole mask now exists in `metis/pinhole_masks.py` (and has been for a while).
